CollapseCategories_controller:
    path: /CollapseCategories/{forum}/{status}/{user}
    defaults: { _controller: alg.CollapseCategories.collapsecategories_ajax_handler:main }
    requirements:
        forum: \d+
