imports:
    - { resource: tables.yml }

services:
    alg.CollapseCategories.listener:
        class: alg\CollapseCategories\event\listener
        arguments:
            - @dbal.conn
            - @template
            - @user
            - %tables.forums_cat_status%
        tags:
            - { name: event.listener }
    alg.CollapseCategories.collapsecategories_ajax_handler:
        class: alg\CollapseCategories\controller\collapsecategories_ajax_handler
        arguments:
            - @dbal.conn
            - %tables.forums_cat_status%

